[project]
name = "quantum_launcher"
version = "1.1"
authors = [
  { name="Dawid Siera", email="dsiera@man.poznan.pl" },
]
description = "Quantum Launcher is modular tool, for solving many problems on many algorithms using many quantum computingbackends"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[tool.setuptools]
py-modules = ["quantum_launcher"]